# Site settings
title: 咸鱼的自我修养
description: 咸鱼的自我修养
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chris Ju
user_description: Be Better
user_title: Solt Fish
email: chris-ju@qq.com
twitter_username: ChrisKingJu
github_username:  Chris-Ju
weibo_username:  鞠擘



exclude: ['package.json', 'src' , 'node_modules']
